// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AccountInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type Attendee struct {
	ID        string     `json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
	Events    []*Event   `json:"events"`
}

type Department struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Moderators []*Account `json:"moderators"`
}

type Event struct {
	ID          string      `json:"id"`
	EventName   string      `json:"eventName"`
	Description string      `json:"description"`
	Images      []*File     `json:"images"`
	Department  *Department `json:"department"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
	DeletedAt   *time.Time  `json:"deletedAt,omitempty"`
}

type EventInput struct {
	EventName   string   `json:"eventName"`
	Description string   `json:"description"`
	Images      []string `json:"images,omitempty"`
}

type File struct {
	ID       string `json:"id"`
	Filename string `json:"filename"`
	ImageURL string `json:"imageURL"`
}

type Mutation struct {
}

type PaginationInput struct {
	Skip *int `json:"skip,omitempty"`
	Take *int `json:"take,omitempty"`
}

type Query struct {
}

type Role string

const (
	RoleUser      Role = "USER"
	RoleAdmin     Role = "ADMIN"
	RoleModerator Role = "MODERATOR"
)

var AllRole = []Role{
	RoleUser,
	RoleAdmin,
	RoleModerator,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleUser, RoleAdmin, RoleModerator:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
