package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"

	authorization "github.com/svladislav00-qq/event-microservices/pkg/auth"
)

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	_ = r.Resolver.Server

	return "pong", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*Account, error) {
	user := authorization.ContextsWithUser(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	res, err := r.Resolver.Server.authClient.GetMe(ctx)
	if err != nil {
		return nil, err
	}

	return &Account{
		ID:       res.Id,
		Email:    res.Email,
		Username: res.Username,
		Role:     res.Role,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
