scalar Time
scalar Upload

enum Role {
  USER
  MODERATOR
  ADMIN
}

enum Status {
  UNKNOWN
  REGISTERED
  CANCELED
}

type Account {
  id: ID!
  email: String!
  username: String!
  role: Role!

  department: String

  createdAt: Time!
  updatedAt: Time!
  deletedAt: Time
}

type Event {
  id: ID!
  name: String!
  description: String!
  department: String!
  createdBy: String!

  startTime: Time!
  endTime: Time!

  capacity: Int
}

input RegisterInput {
  email: String!
  password: String!
  username: String!
}

type Attendee {
  id: String!
  eventID: String!
  userID: String!
  status: Status!
  registeredAt: Time
}

type MyEvent {
  eventID: String!
  status: Status!
  registeredAt: Time!
}

type ExcelFile {
  filename: String!
  content: String!
}


type Query {
  #auth
  ping: String!
  me: Account!

  #event
  getEvent(input: GetEventInput!): Event!
  getEvents(input: GetEventsInput!): [Event!]!

  #attendee
  getUserRegistrations(input: GetUserRegistrationsInput!): [MyEvent!]!
  getEventAttendees(input: GetEventAttendeesInput!): [Attendee!]!
  exportAttendeesTable(eventID: ID!): ExcelFile!
}

type Mutation {
  #auth 
  login(input: LoginInput!): AuthPayload!
  register(input: RegisterInput!): Account!
  promoteToModerator(input: PromoteToModeratorInput!): Account!

  #event 
  createEvent(input: CreateEventInput!): Event!
  updateEvent(input: UpdateEventInput!): Event!
  deleteEvent(input: DeleteEventInput!): Boolean!
  uploadFiles(id: ID!, files: [Upload!]!): [UploadFileResponse!]!

  #attendee
  registerToEvent(input: EventIDInput!): Attendee!
  cancelRegistration(input: EventIDInput!): Boolean!
}

input LoginInput {
  email: String!
  password: String!
}

input PromoteToModeratorInput{
  id: ID!
  department: String!
}

type AuthPayload {
  token: String!
}

input CreateEventInput {
  name: String!
  description: String!
  startTime: Time!
  endTime: Time!
  capacity: Int
}

input UpdateEventInput {
  id: ID!
  name: String
  description: String
  startTime: Time
  endTime: Time
  capacity: Int
}

input DeleteEventInput {
  id: ID!
}

input GetEventInput {
  id: ID!
}

input GetEventsInput {
  skip: Int
  take: Int
}

type UploadFileResponse {
  uploadUrl: String!
  fileKey: String!
}

input GetUserRegistrationsInput {
  skip: Int
  take: Int
}

input EventIDInput {
  eventID: ID!
}

input GetEventAttendeesInput {
  eventID: ID!
  skip: Int
  take: Int
}