scalar Time
scalar Upload

enum Role {
  USER
  MODERATOR
  ADMIN
}

type Account {
  id: ID!
  email: String!
  username: String!
  role: Role!

  department: String

  createdAt: Time!
  updatedAt: Time!
  deletedAt: Time
}

type Event {
  id: ID!
  name: String!
  description: String!
  department: String!
  createdBy: String!

  startTime: Time!
  endTime: Time!

  capacity: Int
}

input RegisterInput {
  email: String!
  password: String!
  username: String!
}


type Query {
  #auth
  ping: String!
  me: Account!

  #event
  getEvent(input: GetEventInput!): Event!
  getEvents(input: GetEventsInput!): [Event!]!
}

type Mutation {
  #auth 
  login(input: LoginInput!): AuthPayload!
  register(input: RegisterInput!): Account!
  promoteToModerator(input: PromoteToModeratorInput!): Account!

  #event 
  createEvent(input: CreateEventInput!): Event!
  updateEvent(input: UpdateEventInput!): Event!
  deleteEvent(input: DeleteEventInput!): Boolean!
  uploadFiles(id: ID!, files: [Upload!]!): [UploadFileResponse!]!
}

input LoginInput {
  email: String!
  password: String!
}

input PromoteToModeratorInput{
  id: ID!
  department: String!
}

type AuthPayload {
  token: String!
}

input CreateEventInput {
  name: String!
  description: String!
  startTime: Time!
  endTime: Time!
  capacity: Int
}

input UpdateEventInput {
  id: ID!
  name: String
  description: String
  startTime: Time
  endTime: Time
  capacity: Int
}

input DeleteEventInput {
  id: ID!
}

input GetEventInput {
  id: ID!
}

input GetEventsInput {
  skip: Int
  take: Int
}

type UploadFileResponse {
  uploadUrl: String!
  fileKey: String!
}