package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"encoding/base64"
	"errors"
	"io"
	"time"

	"github.com/99designs/gqlgen/graphql"
	attendeepb "github.com/svladislav00-qq/event-microservices/attendee/pb"
	authtpb "github.com/svladislav00-qq/event-microservices/auth/pb"
	"github.com/svladislav00-qq/event-microservices/event/pb"
	eventpb "github.com/svladislav00-qq/event-microservices/event/pb"
	authorization "github.com/svladislav00-qq/event-microservices/pkg/auth"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthPayload, error) {
	resp, err := r.Resolver.Server.authClient.Login(ctx, &authtpb.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}

	return &AuthPayload{
		Token: resp.Token,
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input RegisterInput) (*Account, error) {
	resp, err := r.Resolver.Server.authClient.Register(ctx, &authtpb.RegisterRequest{
		Email:    input.Email,
		Password: input.Password,
		Username: input.Username,
	})
	if err != nil {
		return nil, err
	}

	return &Account{
		ID:        resp.Account.Id,
		Email:     resp.Account.Email,
		Username:  resp.Account.Username,
		Role:      Role(resp.Account.Role.String()),
		CreatedAt: resp.Account.CreatedAt.AsTime(),
		UpdatedAt: resp.Account.UpdatedAt.AsTime(),
	}, nil
}

// PromoteToModerator is the resolver for the promoteToModerator field.
func (r *mutationResolver) PromoteToModerator(ctx context.Context, input PromoteToModeratorInput) (*Account, error) {
	ctx = WithAuth(ctx)

	resp, err := r.Resolver.Server.authClient.PromoteToModerator(ctx, &authtpb.PromoteToModeratorRequest{
		UserId:     input.ID,
		Department: input.Department,
	})
	if err != nil {
		return nil, err
	}

	return &Account{
		ID:         resp.Account.Id,
		Email:      resp.Account.Email,
		Username:   resp.Account.Username,
		Role:       Role(resp.Account.Role.String()),
		Department: &resp.Account.Department,
	}, nil
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input CreateEventInput) (*Event, error) {
	var capacity *uint32
	if input.Capacity != nil {
		c := uint32(*input.Capacity)
		capacity = &c
	}

	ctx = WithAuth(ctx)

	resp, err := r.Resolver.Server.eventClient.CreateEvent(
		ctx,
		&eventpb.CreateEventRequest{
			Name:        input.Name,
			Description: input.Description,
			StartTime:   timestamppb.New(input.StartTime),
			EndTime:     timestamppb.New(input.EndTime),
			Capacity:    capacity,
		})

	if err != nil {
		return nil, err
	}

	cap := int(resp.Event.Capacity)

	return &Event{
		ID:          resp.Event.Id,
		Name:        resp.Event.Name,
		Description: resp.Event.Description,
		Department:  resp.Event.Department,
		CreatedBy:   resp.Event.CreatedBy,
		StartTime:   resp.Event.StartTime.AsTime(),
		EndTime:     resp.Event.EndTime.AsTime(),
		CreatedAt:   resp.Event.CreatedAt.AsTime(),
		Capacity:    &cap,
		FileUrls:    resp.Event.FileUrls,
	}, nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, input UpdateEventInput) (*Event, error) {
	ctx = WithAuth(ctx)

	req := &eventpb.UpdateEventRequest{
		Id: input.ID,
	}

	if input.Name != nil {
		req.Name = *input.Name
	}

	if input.Description != nil {
		req.Description = *input.Description
	}

	if input.StartTime != nil {
		req.StartTime = timestamppb.New(*input.StartTime)
	}

	if input.EndTime != nil {
		req.EndTime = timestamppb.New(*input.EndTime)
	}

	if input.Capacity != nil {
		cap := uint32(*input.Capacity)
		req.Capacity = &cap
	}

	resp, err := r.Resolver.Server.eventClient.UpdateEvent(ctx, req)
	if err != nil {
		return nil, err
	}

	cap := int(resp.Event.Capacity)

	return &Event{
		ID:          resp.Event.Id,
		Name:        resp.Event.Name,
		Description: resp.Event.Description,
		Department:  resp.Event.Department,
		StartTime:   resp.Event.StartTime.AsTime(),
		EndTime:     resp.Event.EndTime.AsTime(),
		Capacity:    &cap,
	}, nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, input DeleteEventInput) (bool, error) {
	ctx = WithAuth(ctx)
	_, err := r.Resolver.Server.eventClient.DeleteEvent(ctx, &eventpb.DeleteEventRequest{
		Id: input.ID,
	})
	if err != nil {
		return false, err
	}

	return true, nil
}

// UploadFiles is the resolver for the uploadFiles field.
func (r *mutationResolver) UploadFiles(ctx context.Context, id string, files []*graphql.Upload) ([]*UploadFileResponse, error) {
	var uploads []*pb.FileUpload

	for _, f := range files {
		data, err := io.ReadAll(f.File)
		if err != nil {
			return nil, err
		}

		uploads = append(uploads, &eventpb.FileUpload{
			FileName:    f.Filename,
			ContentType: f.ContentType,
			FileData:    data,
		})
	}

	ctx = WithAuth(ctx)
	resp, err := r.Resolver.Server.eventClient.UploadFiles(ctx, &eventpb.UploadFilesRequest{
		Id:    id,
		Files: uploads,
	})
	if err != nil {
		return nil, err
	}

	var result []*UploadFileResponse
	for _, f := range resp.Files {
		result = append(result, &UploadFileResponse{
			UploadURL: f.UploadUrl,
			FileKey:   f.FileKey,
		})
	}

	return result, nil
}

// RegisterToEvent is the resolver for the registerToEvent field.
func (r *mutationResolver) RegisterToEvent(ctx context.Context, input EventIDInput) (*Attendee, error) {
	ctx = WithAuth(ctx)
	resp, err := r.Resolver.Server.attendeeClient.RegisterToEvent(ctx, &attendeepb.RegisterToEventRequest{
		EventId: input.EventID,
	})
	if err != nil {
		return nil, err
	}

	var registeredAt *time.Time
	if resp.Attendee.RegisteredAt != nil {
		t := resp.Attendee.RegisteredAt.AsTime()
		registeredAt = &t
	}

	return &Attendee{
		ID:           resp.Attendee.Id,
		UserID:       resp.Attendee.UserId,
		EventID:      resp.Attendee.EventId,
		Status:       Status(resp.Attendee.Status.String()),
		RegisteredAt: registeredAt,
	}, nil
}

// CancelRegistration is the resolver for the cancelRegistration field.
func (r *mutationResolver) CancelRegistration(ctx context.Context, input EventIDInput) (bool, error) {
	ctx = WithAuth(ctx)
	_, err := r.Resolver.Server.attendeeClient.CancelRegistration(ctx, &attendeepb.CancelRegistrationRequest{
		EventId: input.EventID,
	})
	if err != nil {
		return false, err
	}

	return true, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	_ = r.Resolver.Server

	return "pong", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*Account, error) {
	user, _ := authorization.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	ctx = WithAuth(ctx)
	resp, err := r.Server.authClient.GetMe(ctx, &authtpb.GetMeRequest{})
	if err != nil {
		return nil, err
	}

	return &Account{
		ID:         resp.Account.Id,
		Email:      resp.Account.Email,
		Username:   resp.Account.Username,
		Role:       Role(resp.Account.Role.String()),
		Department: &resp.Account.Department,
	}, nil
}

// GetEvent is the resolver for the getEvent field.
func (r *queryResolver) GetEvent(ctx context.Context, input GetEventInput) (*Event, error) {
	ctx = WithAuth(ctx)
	resp, err := r.Server.eventClient.GetEvent(ctx, &eventpb.GetEventRequest{
		Id: input.ID,
	})
	if err != nil {
		return nil, err
	}

	cap := int(resp.Event.Capacity)
	fileUrls := resp.Event.FileUrls
	if fileUrls == nil {
		fileUrls = []string{}
	}

	return &Event{
		ID:          resp.Event.Id,
		Name:        resp.Event.Name,
		Description: resp.Event.Description,
		Department:  resp.Event.Department,
		CreatedBy:   resp.Event.CreatedBy,
		StartTime:   resp.Event.StartTime.AsTime(),
		EndTime:     resp.Event.EndTime.AsTime(),
		Capacity:    &cap,
		CreatedAt:   resp.Event.CreatedAt.AsTime(),
		FileUrls:    fileUrls,
	}, nil
}

// GetEvents is the resolver for the getEvents field.
func (r *queryResolver) GetEvents(ctx context.Context, input GetEventsInput) ([]*Event, error) {
	ctx = WithAuth(ctx)
	resp, err := r.Server.eventClient.GetEvents(ctx, &pb.GetEventsRequest{
		Skip: uint64(*input.Skip),
		Take: uint64(*input.Take),
	})
	if err != nil {
		return nil, err
	}

	var result []*Event

	for _, e := range resp.Events {
		var capacity *int
		if e.Capacity != 0 {
			c := int(e.Capacity)
			capacity = &c
		}

		fileUrls := e.FileUrls
		if fileUrls == nil {
			fileUrls = []string{}
		}
		result = append(result, &Event{
			ID:          e.Id,
			Name:        e.Name,
			Description: e.Description,
			Department:  e.Department,
			CreatedBy:   e.CreatedBy,
			StartTime:   e.StartTime.AsTime(),
			EndTime:     e.EndTime.AsTime(),
			Capacity:    capacity,
			CreatedAt:   e.CreatedAt.AsTime(),
			FileUrls:    fileUrls,
		})
	}

	return result, nil
}

// GetUserRegistrations is the resolver for the getUserRegistrations field.
func (r *queryResolver) GetUserRegistrations(ctx context.Context, input GetUserRegistrationsInput) ([]*MyEvent, error) {
	var skip uint32
	if input.Skip != nil {
		skip = uint32(*input.Skip)
	}

	var take uint32
	if input.Take != nil {
		take = uint32(*input.Take)
	}

	ctx = WithAuth(ctx)
	resp, err := r.Resolver.Server.attendeeClient.GetUserRegistrations(ctx, &attendeepb.GetUserRegistrationsRequest{
		Skip: uint64(skip),
		Take: uint64(take),
	})
	if err != nil {
		return nil, err
	}

	var result []*MyEvent
	for _, e := range resp.Events {
		result = append(result, &MyEvent{
			EventID:      e.EventId,
			Status:       Status(e.Status.String()),
			RegisteredAt: e.RegisteredAt.AsTime(),
		})
	}

	return result, nil
}

// GetEventAttendees is the resolver for the getEventAttendees field.
func (r *queryResolver) GetEventAttendees(ctx context.Context, input GetEventAttendeesInput) ([]*Attendee, error) {
	var skip uint32
	if input.Skip != nil {
		skip = uint32(*input.Skip)
	}

	var take uint32
	if input.Take != nil {
		take = uint32(*input.Take)
	}

	ctx = WithAuth(ctx)
	resp, err := r.Resolver.Server.attendeeClient.GetEventAttendees(ctx, &attendeepb.GetEventAttendeesRequest{
		Skip:    uint64(skip),
		Take:    uint64(take),
		EventId: input.EventID,
	})
	if err != nil {
		return nil, err
	}

	var result []*Attendee
	for _, e := range resp.Attendees {
		var registeredAt *time.Time
		if e.RegisteredAt != nil {
			t := e.RegisteredAt.AsTime()
			registeredAt = &t
		}
		result = append(result, &Attendee{
			ID:           e.Id,
			UserID:       e.UserId,
			EventID:      e.EventId,
			Status:       Status(e.Status.String()),
			RegisteredAt: registeredAt,
		})
	}

	return result, nil
}

// ExportAttendeesTable is the resolver for the exportAttendeesTable field.
func (r *queryResolver) ExportAttendeesTable(ctx context.Context, eventID string) (*ExcelFile, error) {
	ctx = WithAuth(ctx)
	resp, err := r.Resolver.Server.attendeeClient.ExportAttendeesTable(ctx, &attendeepb.ExportAttendeesTableRequest{
		EventId: eventID,
	})
	if err != nil {
		return nil, err
	}

	encoded := base64.StdEncoding.EncodeToString(resp.File)

	return &ExcelFile{
		Filename: resp.Filename,
		Content:  encoded,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
