scalar Time
scalar Upload

enum Role {
    USER
    ADMIN
    MODERATOR
}

type Account {
    id: ID!
    email: String!
    password: String
    username: String!
    roles: [Role!]!
    department: Department
    createdAt: Time!
    updatedAt: Time!
    deletedAt: Time
}



type Department {
    id: ID!
    name: String!
    moderators: [Account!]!
}

type Event {
    id: ID!
    eventName: String!
    description: String!
    images:[File!]!
    department: Department!
    createdAt: Time!
    updatedAt: Time!
    deletedAt: Time
}

type File {
    id: ID!
    filename: String!
    imageURL: String!
}

type Attendee {
    id: ID!
    createdAt: Time!
    updatedAt: Time!
    deletedAt: Time
    events: [Event!]!
}

input AccountInput {
    email: String!
    password: String!
    username: String!
}

input EventInput {
    eventName: String!
    description: String!
    images: [String!]
}

input PaginationInput {
    skip: Int
    take: Int
}

type Mutation {
    uploadedFile(file: Upload!): File!
    createAccount(account: AccountInput): Account
    createEvent(event: EventInput): Event
    registerForEvent(eventID: ID!): Attendee!
}

type Query {
    accounts(pagination: PaginationInput, id: ID): [Account!]!
    events(pagination: PaginationInput, query: ID, id: ID): [Event!]!
    attendeeForEvent(pagination: PaginationInput, eventId: ID!): [Attendee!]!
}
