// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: attendee.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttendeeService_RegisterToEvent_FullMethodName      = "/pb.AttendeeService/RegisterToEvent"
	AttendeeService_CancelRegistration_FullMethodName   = "/pb.AttendeeService/CancelRegistration"
	AttendeeService_GetUserRegistrations_FullMethodName = "/pb.AttendeeService/GetUserRegistrations"
	AttendeeService_GetEventAttendees_FullMethodName    = "/pb.AttendeeService/GetEventAttendees"
	AttendeeService_ExportAttendeesTable_FullMethodName = "/pb.AttendeeService/ExportAttendeesTable"
)

// AttendeeServiceClient is the client API for AttendeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttendeeServiceClient interface {
	RegisterToEvent(ctx context.Context, in *RegisterToEventRequest, opts ...grpc.CallOption) (*RegisterToEventResponse, error)
	CancelRegistration(ctx context.Context, in *CancelRegistrationRequest, opts ...grpc.CallOption) (*CancelRegistrationResponse, error)
	GetUserRegistrations(ctx context.Context, in *GetUserRegistrationsRequest, opts ...grpc.CallOption) (*GetUserRegistrationsResponse, error)
	GetEventAttendees(ctx context.Context, in *GetEventAttendeesRequest, opts ...grpc.CallOption) (*GetEventAttendeesResponse, error)
	ExportAttendeesTable(ctx context.Context, in *ExportAttendeeTableRequest, opts ...grpc.CallOption) (*ExportAttendeeTableResponse, error)
}

type attendeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttendeeServiceClient(cc grpc.ClientConnInterface) AttendeeServiceClient {
	return &attendeeServiceClient{cc}
}

func (c *attendeeServiceClient) RegisterToEvent(ctx context.Context, in *RegisterToEventRequest, opts ...grpc.CallOption) (*RegisterToEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterToEventResponse)
	err := c.cc.Invoke(ctx, AttendeeService_RegisterToEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendeeServiceClient) CancelRegistration(ctx context.Context, in *CancelRegistrationRequest, opts ...grpc.CallOption) (*CancelRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRegistrationResponse)
	err := c.cc.Invoke(ctx, AttendeeService_CancelRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendeeServiceClient) GetUserRegistrations(ctx context.Context, in *GetUserRegistrationsRequest, opts ...grpc.CallOption) (*GetUserRegistrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRegistrationsResponse)
	err := c.cc.Invoke(ctx, AttendeeService_GetUserRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendeeServiceClient) GetEventAttendees(ctx context.Context, in *GetEventAttendeesRequest, opts ...grpc.CallOption) (*GetEventAttendeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventAttendeesResponse)
	err := c.cc.Invoke(ctx, AttendeeService_GetEventAttendees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendeeServiceClient) ExportAttendeesTable(ctx context.Context, in *ExportAttendeeTableRequest, opts ...grpc.CallOption) (*ExportAttendeeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportAttendeeTableResponse)
	err := c.cc.Invoke(ctx, AttendeeService_ExportAttendeesTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttendeeServiceServer is the server API for AttendeeService service.
// All implementations must embed UnimplementedAttendeeServiceServer
// for forward compatibility.
type AttendeeServiceServer interface {
	RegisterToEvent(context.Context, *RegisterToEventRequest) (*RegisterToEventResponse, error)
	CancelRegistration(context.Context, *CancelRegistrationRequest) (*CancelRegistrationResponse, error)
	GetUserRegistrations(context.Context, *GetUserRegistrationsRequest) (*GetUserRegistrationsResponse, error)
	GetEventAttendees(context.Context, *GetEventAttendeesRequest) (*GetEventAttendeesResponse, error)
	ExportAttendeesTable(context.Context, *ExportAttendeeTableRequest) (*ExportAttendeeTableResponse, error)
	mustEmbedUnimplementedAttendeeServiceServer()
}

// UnimplementedAttendeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttendeeServiceServer struct{}

func (UnimplementedAttendeeServiceServer) RegisterToEvent(context.Context, *RegisterToEventRequest) (*RegisterToEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterToEvent not implemented")
}
func (UnimplementedAttendeeServiceServer) CancelRegistration(context.Context, *CancelRegistrationRequest) (*CancelRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRegistration not implemented")
}
func (UnimplementedAttendeeServiceServer) GetUserRegistrations(context.Context, *GetUserRegistrationsRequest) (*GetUserRegistrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRegistrations not implemented")
}
func (UnimplementedAttendeeServiceServer) GetEventAttendees(context.Context, *GetEventAttendeesRequest) (*GetEventAttendeesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventAttendees not implemented")
}
func (UnimplementedAttendeeServiceServer) ExportAttendeesTable(context.Context, *ExportAttendeeTableRequest) (*ExportAttendeeTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportAttendeesTable not implemented")
}
func (UnimplementedAttendeeServiceServer) mustEmbedUnimplementedAttendeeServiceServer() {}
func (UnimplementedAttendeeServiceServer) testEmbeddedByValue()                         {}

// UnsafeAttendeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttendeeServiceServer will
// result in compilation errors.
type UnsafeAttendeeServiceServer interface {
	mustEmbedUnimplementedAttendeeServiceServer()
}

func RegisterAttendeeServiceServer(s grpc.ServiceRegistrar, srv AttendeeServiceServer) {
	// If the following call panics, it indicates UnimplementedAttendeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttendeeService_ServiceDesc, srv)
}

func _AttendeeService_RegisterToEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterToEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendeeServiceServer).RegisterToEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendeeService_RegisterToEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendeeServiceServer).RegisterToEvent(ctx, req.(*RegisterToEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendeeService_CancelRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendeeServiceServer).CancelRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendeeService_CancelRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendeeServiceServer).CancelRegistration(ctx, req.(*CancelRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendeeService_GetUserRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRegistrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendeeServiceServer).GetUserRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendeeService_GetUserRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendeeServiceServer).GetUserRegistrations(ctx, req.(*GetUserRegistrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendeeService_GetEventAttendees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventAttendeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendeeServiceServer).GetEventAttendees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendeeService_GetEventAttendees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendeeServiceServer).GetEventAttendees(ctx, req.(*GetEventAttendeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendeeService_ExportAttendeesTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportAttendeeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendeeServiceServer).ExportAttendeesTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendeeService_ExportAttendeesTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendeeServiceServer).ExportAttendeesTable(ctx, req.(*ExportAttendeeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttendeeService_ServiceDesc is the grpc.ServiceDesc for AttendeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttendeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AttendeeService",
	HandlerType: (*AttendeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterToEvent",
			Handler:    _AttendeeService_RegisterToEvent_Handler,
		},
		{
			MethodName: "CancelRegistration",
			Handler:    _AttendeeService_CancelRegistration_Handler,
		},
		{
			MethodName: "GetUserRegistrations",
			Handler:    _AttendeeService_GetUserRegistrations_Handler,
		},
		{
			MethodName: "GetEventAttendees",
			Handler:    _AttendeeService_GetEventAttendees_Handler,
		},
		{
			MethodName: "ExportAttendeesTable",
			Handler:    _AttendeeService_ExportAttendeesTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "attendee.proto",
}
