// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: attendee.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN    Status = 0
	Status_STATUS_REGISTERED Status = 1
	Status_STATUS_CANCELED   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_REGISTERED",
		2: "STATUS_CANCELED",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":    0,
		"STATUS_REGISTERED": 1,
		"STATUS_CANCELED":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_attendee_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_attendee_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{0}
}

type Attendee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attendee) Reset() {
	*x = Attendee{}
	mi := &file_attendee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attendee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attendee) ProtoMessage() {}

func (x *Attendee) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attendee.ProtoReflect.Descriptor instead.
func (*Attendee) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{0}
}

func (x *Attendee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attendee) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Attendee) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Attendee) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *Attendee) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type MyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyEvent) Reset() {
	*x = MyEvent{}
	mi := &file_attendee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyEvent) ProtoMessage() {}

func (x *MyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyEvent.ProtoReflect.Descriptor instead.
func (*MyEvent) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{1}
}

func (x *MyEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MyEvent) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *MyEvent) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type RegisterToEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterToEventRequest) Reset() {
	*x = RegisterToEventRequest{}
	mi := &file_attendee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterToEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterToEventRequest) ProtoMessage() {}

func (x *RegisterToEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterToEventRequest.ProtoReflect.Descriptor instead.
func (*RegisterToEventRequest) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterToEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type RegisterToEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendee      *Attendee              `protobuf:"bytes,1,opt,name=attendee,proto3" json:"attendee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterToEventResponse) Reset() {
	*x = RegisterToEventResponse{}
	mi := &file_attendee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterToEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterToEventResponse) ProtoMessage() {}

func (x *RegisterToEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterToEventResponse.ProtoReflect.Descriptor instead.
func (*RegisterToEventResponse) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterToEventResponse) GetAttendee() *Attendee {
	if x != nil {
		return x.Attendee
	}
	return nil
}

type CancelRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRegistrationRequest) Reset() {
	*x = CancelRegistrationRequest{}
	mi := &file_attendee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegistrationRequest) ProtoMessage() {}

func (x *CancelRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CancelRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRegistrationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type CancelRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRegistrationResponse) Reset() {
	*x = CancelRegistrationResponse{}
	mi := &file_attendee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegistrationResponse) ProtoMessage() {}

func (x *CancelRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegistrationResponse.ProtoReflect.Descriptor instead.
func (*CancelRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{5}
}

type GetUserRegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRegistrationsRequest) Reset() {
	*x = GetUserRegistrationsRequest{}
	mi := &file_attendee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRegistrationsRequest) ProtoMessage() {}

func (x *GetUserRegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRegistrationsRequest.ProtoReflect.Descriptor instead.
func (*GetUserRegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRegistrationsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetUserRegistrationsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *GetUserRegistrationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRegistrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*MyEvent             `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRegistrationsResponse) Reset() {
	*x = GetUserRegistrationsResponse{}
	mi := &file_attendee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRegistrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRegistrationsResponse) ProtoMessage() {}

func (x *GetUserRegistrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRegistrationsResponse.ProtoReflect.Descriptor instead.
func (*GetUserRegistrationsResponse) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRegistrationsResponse) GetEvents() []*MyEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventAttendeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventAttendeesRequest) Reset() {
	*x = GetEventAttendeesRequest{}
	mi := &file_attendee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventAttendeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventAttendeesRequest) ProtoMessage() {}

func (x *GetEventAttendeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventAttendeesRequest.ProtoReflect.Descriptor instead.
func (*GetEventAttendeesRequest) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventAttendeesRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetEventAttendeesRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *GetEventAttendeesRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventAttendeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendees     []*Attendee            `protobuf:"bytes,1,rep,name=attendees,proto3" json:"attendees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventAttendeesResponse) Reset() {
	*x = GetEventAttendeesResponse{}
	mi := &file_attendee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventAttendeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventAttendeesResponse) ProtoMessage() {}

func (x *GetEventAttendeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventAttendeesResponse.ProtoReflect.Descriptor instead.
func (*GetEventAttendeesResponse) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventAttendeesResponse) GetAttendees() []*Attendee {
	if x != nil {
		return x.Attendees
	}
	return nil
}

type ExportAttendeesTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAttendeesTableRequest) Reset() {
	*x = ExportAttendeesTableRequest{}
	mi := &file_attendee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAttendeesTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAttendeesTableRequest) ProtoMessage() {}

func (x *ExportAttendeesTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAttendeesTableRequest.ProtoReflect.Descriptor instead.
func (*ExportAttendeesTableRequest) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{10}
}

func (x *ExportAttendeesTableRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ExportAttendeesTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAttendeesTableResponse) Reset() {
	*x = ExportAttendeesTableResponse{}
	mi := &file_attendee_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAttendeesTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAttendeesTableResponse) ProtoMessage() {}

func (x *ExportAttendeesTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendee_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAttendeesTableResponse.ProtoReflect.Descriptor instead.
func (*ExportAttendeesTableResponse) Descriptor() ([]byte, []int) {
	return file_attendee_proto_rawDescGZIP(), []int{11}
}

func (x *ExportAttendeesTableResponse) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ExportAttendeesTableResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_attendee_proto protoreflect.FileDescriptor

const file_attendee_proto_rawDesc = "" +
	"\n" +
	"\x0eattendee.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\bAttendee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\"\n" +
	"\x06status\x18\x04 \x01(\x0e2\n" +
	".pb.StatusR\x06status\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"\x89\x01\n" +
	"\aMyEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\"\n" +
	"\x06status\x18\x02 \x01(\x0e2\n" +
	".pb.StatusR\x06status\x12?\n" +
	"\rregistered_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"3\n" +
	"\x16RegisterToEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"C\n" +
	"\x17RegisterToEventResponse\x12(\n" +
	"\battendee\x18\x01 \x01(\v2\f.pb.AttendeeR\battendee\"6\n" +
	"\x19CancelRegistrationRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\x1c\n" +
	"\x1aCancelRegistrationResponse\"^\n" +
	"\x1bGetUserRegistrationsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"C\n" +
	"\x1cGetUserRegistrationsResponse\x12#\n" +
	"\x06events\x18\x01 \x03(\v2\v.pb.MyEventR\x06events\"]\n" +
	"\x18GetEventAttendeesRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"G\n" +
	"\x19GetEventAttendeesResponse\x12*\n" +
	"\tattendees\x18\x01 \x03(\v2\f.pb.AttendeeR\tattendees\"8\n" +
	"\x1bExportAttendeesTableRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"N\n" +
	"\x1cExportAttendeesTableResponse\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename*H\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11STATUS_REGISTERED\x10\x01\x12\x13\n" +
	"\x0fSTATUS_CANCELED\x10\x022\xc4\x03\n" +
	"\x0fAttendeeService\x12L\n" +
	"\x0fRegisterToEvent\x12\x1a.pb.RegisterToEventRequest\x1a\x1b.pb.RegisterToEventResponse\"\x00\x12U\n" +
	"\x12CancelRegistration\x12\x1d.pb.CancelRegistrationRequest\x1a\x1e.pb.CancelRegistrationResponse\"\x00\x12[\n" +
	"\x14GetUserRegistrations\x12\x1f.pb.GetUserRegistrationsRequest\x1a .pb.GetUserRegistrationsResponse\"\x00\x12R\n" +
	"\x11GetEventAttendees\x12\x1c.pb.GetEventAttendeesRequest\x1a\x1d.pb.GetEventAttendeesResponse\"\x00\x12[\n" +
	"\x14ExportAttendeesTable\x12\x1f.pb.ExportAttendeesTableRequest\x1a .pb.ExportAttendeesTableResponse\"\x00B<Z:github.com/svladislav00-qq/event-microservices/attendee/pbb\x06proto3"

var (
	file_attendee_proto_rawDescOnce sync.Once
	file_attendee_proto_rawDescData []byte
)

func file_attendee_proto_rawDescGZIP() []byte {
	file_attendee_proto_rawDescOnce.Do(func() {
		file_attendee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attendee_proto_rawDesc), len(file_attendee_proto_rawDesc)))
	})
	return file_attendee_proto_rawDescData
}

var file_attendee_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_attendee_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_attendee_proto_goTypes = []any{
	(Status)(0),                          // 0: pb.Status
	(*Attendee)(nil),                     // 1: pb.Attendee
	(*MyEvent)(nil),                      // 2: pb.MyEvent
	(*RegisterToEventRequest)(nil),       // 3: pb.RegisterToEventRequest
	(*RegisterToEventResponse)(nil),      // 4: pb.RegisterToEventResponse
	(*CancelRegistrationRequest)(nil),    // 5: pb.CancelRegistrationRequest
	(*CancelRegistrationResponse)(nil),   // 6: pb.CancelRegistrationResponse
	(*GetUserRegistrationsRequest)(nil),  // 7: pb.GetUserRegistrationsRequest
	(*GetUserRegistrationsResponse)(nil), // 8: pb.GetUserRegistrationsResponse
	(*GetEventAttendeesRequest)(nil),     // 9: pb.GetEventAttendeesRequest
	(*GetEventAttendeesResponse)(nil),    // 10: pb.GetEventAttendeesResponse
	(*ExportAttendeesTableRequest)(nil),  // 11: pb.ExportAttendeesTableRequest
	(*ExportAttendeesTableResponse)(nil), // 12: pb.ExportAttendeesTableResponse
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_attendee_proto_depIdxs = []int32{
	0,  // 0: pb.Attendee.status:type_name -> pb.Status
	13, // 1: pb.Attendee.registered_at:type_name -> google.protobuf.Timestamp
	0,  // 2: pb.MyEvent.status:type_name -> pb.Status
	13, // 3: pb.MyEvent.registered_at:type_name -> google.protobuf.Timestamp
	1,  // 4: pb.RegisterToEventResponse.attendee:type_name -> pb.Attendee
	2,  // 5: pb.GetUserRegistrationsResponse.events:type_name -> pb.MyEvent
	1,  // 6: pb.GetEventAttendeesResponse.attendees:type_name -> pb.Attendee
	3,  // 7: pb.AttendeeService.RegisterToEvent:input_type -> pb.RegisterToEventRequest
	5,  // 8: pb.AttendeeService.CancelRegistration:input_type -> pb.CancelRegistrationRequest
	7,  // 9: pb.AttendeeService.GetUserRegistrations:input_type -> pb.GetUserRegistrationsRequest
	9,  // 10: pb.AttendeeService.GetEventAttendees:input_type -> pb.GetEventAttendeesRequest
	11, // 11: pb.AttendeeService.ExportAttendeesTable:input_type -> pb.ExportAttendeesTableRequest
	4,  // 12: pb.AttendeeService.RegisterToEvent:output_type -> pb.RegisterToEventResponse
	6,  // 13: pb.AttendeeService.CancelRegistration:output_type -> pb.CancelRegistrationResponse
	8,  // 14: pb.AttendeeService.GetUserRegistrations:output_type -> pb.GetUserRegistrationsResponse
	10, // 15: pb.AttendeeService.GetEventAttendees:output_type -> pb.GetEventAttendeesResponse
	12, // 16: pb.AttendeeService.ExportAttendeesTable:output_type -> pb.ExportAttendeesTableResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_attendee_proto_init() }
func file_attendee_proto_init() {
	if File_attendee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attendee_proto_rawDesc), len(file_attendee_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attendee_proto_goTypes,
		DependencyIndexes: file_attendee_proto_depIdxs,
		EnumInfos:         file_attendee_proto_enumTypes,
		MessageInfos:      file_attendee_proto_msgTypes,
	}.Build()
	File_attendee_proto = out.File
	file_attendee_proto_goTypes = nil
	file_attendee_proto_depIdxs = nil
}
